// @NOTICE This file is generated by sav-cli.

/* eslint quotes: ["off"] */
import Element from './Element/Element.vue'
import ElementTabs from './Element/ElementTabs.vue'
import ElementButtons from './Element/ElementButtons.vue'
import Home from './Home/Home.vue'
import HomeIndex from './Home/HomeIndex.vue'
import Page from './Page/Page.vue'
import PageLogin from './Page/PageLogin.vue'
import PageRegister from './Page/PageRegister.vue'

export default [
  {
    component: Element,
    path: "/element",
    children: [
      {
        component: ElementTabs,
        name: "ElementTabs",
        path: "tabs"
      },
      {
        component: ElementButtons,
        name: "ElementButtons",
        path: "buttons"
      }
    ]
  },
  {
    component: Home,
    path: "/",
    children: [
      {
        component: HomeIndex,
        name: "HomeIndex",
        path: ""
      }
    ]
  },
  {
    component: Page,
    path: "/page",
    children: [
      {
        component: PageLogin,
        name: "PageLogin",
        path: "login"
      },
      {
        component: PageRegister,
        name: "PageRegister",
        path: "register"
      }
    ]
  }
]
