// @NOTICE This file is generated by sav-cli.

/* eslint quotes: ["off"] */
module.exports = {
  routes: {
    select: {
      method: "GET",
      title: "选择框"
    },
    index: {
      method: "GET",
      title: "元素",
      path: ""
    }
  }
}
