// @NOTICE This file is generated by sav-cli.

/* eslint quotes: ["off"] */
module.exports = {
  routes: {
    tabs: {
      method: "GET",
      title: "标签页"
    },
    buttons: {
      method: "GET",
      title: "按钮"
    }
  }
}
