// @NOTICE This file is generated by sav-cli.

/* eslint quotes: ["off"] */
module.exports = {
  path: "",
  routes: {
    index: {
      method: "GET",
      path: "",
      title: "仪表板"
    }
  }
}
