// @NOTICE This file is generated by sav-cli.

module.exports = {
  Component: require('./Component'),
  Element: require('./Element'),
  Home: require('./Home'),
  Layout: require('./Layout'),
  Page: require('./Page')
}
