// @NOTICE This file is generated by sav-cli.

/* eslint quotes: ["off"] */
module.exports = {
  routes: {
    tile: {
      method: "GET",
      title: "tile"
    },
    grid: {
      method: "GET",
      title: "grid"
    },
    index: {
      method: "GET",
      title: "布局",
      path: ""
    }
  }
}
