// @NOTICE This file is generated by sav-cli.

/* eslint quotes: ["off"] */
module.exports = {
  routes: {
    login: {
      method: "GET",
      title: "登录页面"
    },
    register: {
      method: "GET",
      title: "注册页面"
    }
  }
}
